### ISSUE TITLE
Nuget would be lovely :-)

### ISSUE THREAD

**Issue by rasmuseeg** [bjarnef/Switcher#2]
Hi There,

If this package need anything, it could be nuget package

**Comment by bjarnef** [comment]
Indeed! :)
I will take a look at it, when I have some extra time.

**Comment by KevinJump** [comment]
Hi 

i've submitted a PR https://github.com/bjarnef/Switcher/pull/5 with nuget package stuff in it.

**Comment by bjarnef** [comment]
I have published a new release of Switcher https://our.umbraco.org/projects/backoffice-extensions/switcher/ and added the NuGet package here https://www.nuget.org/packages/Our.Umbraco.Switcher

👍 :tada: 🙌
