### ISSUE TITLE
Needs a value converter

### ISSUE THREAD

**Issue by skttl** [bjarnef/Switcher#6]
ModelsBuilder returns the value of this as an object. I created a value converter for it, so you get a boolean value.

PR coming

**Comment by skttl** [comment]
#7

**Comment by bjarnef** [comment]
Thanks for the PR @skttl , but I would prefer to disquss this issue http://issues.umbraco.org/issue/U4-10005 and hopefully make it possible the reuse core property value converters, e.g. like we already can reuse core directives/components and property editors.

**Comment by skttl** [comment]
Agree, that issue would be great to have in Umbraco.

man. 30. okt. 2017 kl. 11.55 skrev Bjarne Fyrstenborg <
notifications@github.com>:

**Comment by ronaldbarendse** [comment]
I agree with @bjarnef that there should be a generic `PropertyValueConverter` for this, but for a drop-in fix, the following code should do and could be included in the readme (since at first I didn't see the closed issue and PR):

```c#
[PropertyValueType(typeof(bool))]
[PropertyValueCache(PropertyCacheValue.All, PropertyCacheLevel.Content)]
public class SwitcherValueConverter : Umbraco.Core.PropertyEditors.ValueConverters.YesNoValueConverter
{
	public override bool IsConverter(PublishedPropertyType propertyType)
	{
		return propertyType.PropertyEditorAlias == "Our.Umbraco.Switcher";
	}
}
```
